name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"   # e.g., v0.2.1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      # (Optional) quick directory sanity
      - name: Debug tree
        run: |
          pwd && ls -la
          test -f web/package.json && echo "Found web/package.json" || echo "web/package.json NOT found"
          test -f web/index.html && echo "Found web/index.html" || echo "web/index.html NOT found"

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: web/package-lock.json

      - name: Build Svelte frontend (web/)
        working-directory: web
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
          npm run build

      - name: Copy frontend into Python package
        run: |
          mkdir -p saterys/static
          test -f web/dist/index.html || { echo "❌ web/dist/index.html not found after build"; exit 1; }
          rsync -a web/dist/ saterys/static/
          test -f saterys/static/index.html || { echo "❌ saterys/static/index.html missing after copy"; exit 1; }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build wheel/sdist
        run: |
          python -m pip install --upgrade pip build twine
          rm -rf dist build *.egg-info
          python -m build
          ls -lh dist

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --non-interactive dist/*
