name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
      TWINE_USERNAME: __token__

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Frontend (Svelte) ----------
      # Only run if the saterys/web frontend exists
      - name: Setup Node
        if: ${{ hashFiles('saterys/web/package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: saterys/web/package-lock.json

      - name: Install web deps
        if: ${{ hashFiles('saterys/web/package.json') != '' }}
        working-directory: saterys/web
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build web
        if: ${{ hashFiles('saterys/web/package.json') != '' }}
        working-directory: saterys/web
        run: npm run build

      - name: Verify static bundle exists
        shell: bash
        run: |
          test -f saterys/static/index.html || { echo "::error ::saterys/static/index.html not found"; exit 1; }

      # ---------- Python package ----------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tools
        run: python -m pip install -U pip build twine

      - name: Build sdist and wheel
        run: |
          rm -rf dist build *.egg-info
          python -m build
          twine check dist/*

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --non-interactive dist/*
