name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"   # e.g., v0.2.1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip build twine

      - name: Build Svelte frontend
        working-directory: web
        run: |
          npm ci
          npm run build

      - name: Copy frontend into package
        run: |
          mkdir -p saterys/static
          cp -r web/dist/* saterys/static/

      - name: Build wheel/sdist
        run: |
          rm -rf dist build *.egg-info
          python -m build
          ls -lh dist

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --non-interactive dist/*

